var subCate = {
    1: [
        {
            link_product_list: "/category/집-내놓기/24/",
            name: "집 내놓기",
            param: "?cate_no=24",
            cate_no: 24,
            parent_cate_no: 1,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/집-구하기/25/",
            name: "집 구하기",
            param: "?cate_no=25",
            cate_no: 25,
            parent_cate_no: 1,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/부동산뉴스/26/",
            name: "부동산뉴스",
            param: "?cate_no=26",
            cate_no: 26,
            parent_cate_no: 1,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/블로그/27/",
            name: "블로그",
            param: "?cate_no=27",
            cate_no: 27,
            parent_cate_no: 1,
            design_page_url: "product/list.html",
            like_count: 0,
        },
    ],
    25: [
        {
            link_product_list: "/category/서울시/77/",
            name: "서울시",
            param: "?cate_no=77",
            cate_no: 77,
            parent_cate_no: 25,
            design_page_url: "product/list.html",
            like_count: 0,
        },
    ],
    27: [
        {
            link_product_list: "/category/정치/34/",
            name: "정치",
            param: "?cate_no=34",
            cate_no: 34,
            parent_cate_no: 27,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/사회/35/",
            name: "사회",
            param: "?cate_no=35",
            cate_no: 35,
            parent_cate_no: 27,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/경제/42/",
            name: "경제",
            param: "?cate_no=42",
            cate_no: 42,
            parent_cate_no: 27,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/문화/43/",
            name: "문화",
            param: "?cate_no=43",
            cate_no: 43,
            parent_cate_no: 27,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/과학/44/",
            name: "과학",
            param: "?cate_no=44",
            cate_no: 44,
            parent_cate_no: 27,
            design_page_url: "product/list.html",
            like_count: 0,
        },
    ],
    46: [
        {
            link_product_list: "/category/개포동/61/",
            name: "개포동",
            param: "?cate_no=61",
            cate_no: 61,
            parent_cate_no: 46,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/논현동/62/",
            name: "논현동",
            param: "?cate_no=62",
            cate_no: 62,
            parent_cate_no: 46,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/대치동/63/",
            name: "대치동",
            param: "?cate_no=63",
            cate_no: 63,
            parent_cate_no: 46,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/도곡동/64/",
            name: "도곡동",
            param: "?cate_no=64",
            cate_no: 64,
            parent_cate_no: 46,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/삼성동/67/",
            name: "삼성동",
            param: "?cate_no=67",
            cate_no: 67,
            parent_cate_no: 46,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/세곡동/68/",
            name: "세곡동",
            param: "?cate_no=68",
            cate_no: 68,
            parent_cate_no: 46,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/수서동/69/",
            name: "수서동",
            param: "?cate_no=69",
            cate_no: 69,
            parent_cate_no: 46,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/신사동/70/",
            name: "신사동",
            param: "?cate_no=70",
            cate_no: 70,
            parent_cate_no: 46,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/압구정동/71/",
            name: "압구정동",
            param: "?cate_no=71",
            cate_no: 71,
            parent_cate_no: 46,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/역삼동/72/",
            name: "역삼동",
            param: "?cate_no=72",
            cate_no: 72,
            parent_cate_no: 46,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/율현동/73/",
            name: "율현동",
            param: "?cate_no=73",
            cate_no: 73,
            parent_cate_no: 46,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/일원동/74/",
            name: "일원동",
            param: "?cate_no=74",
            cate_no: 74,
            parent_cate_no: 46,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/자곡동/75/",
            name: "자곡동",
            param: "?cate_no=75",
            cate_no: 75,
            parent_cate_no: 46,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/청담동/76/",
            name: "청담동",
            param: "?cate_no=76",
            cate_no: 76,
            parent_cate_no: 46,
            design_page_url: "product/list.html",
            like_count: 0,
        },
    ],
    54: [
        {
            link_product_list: "/category/공릉동/56/",
            name: "공릉동",
            param: "?cate_no=56",
            cate_no: 56,
            parent_cate_no: 54,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/상계동/57/",
            name: "상계동",
            param: "?cate_no=57",
            cate_no: 57,
            parent_cate_no: 54,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/월계동/58/",
            name: "월계동",
            param: "?cate_no=58",
            cate_no: 58,
            parent_cate_no: 54,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/중계동/59/",
            name: "중계동",
            param: "?cate_no=59",
            cate_no: 59,
            parent_cate_no: 54,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/하계동/60/",
            name: "하계동",
            param: "?cate_no=60",
            cate_no: 60,
            parent_cate_no: 54,
            design_page_url: "product/list.html",
            like_count: 0,
        },
    ],
    77: [
        {
            link_product_list: "/category/강남구/46/",
            name: "강남구",
            param: "?cate_no=46",
            cate_no: 46,
            parent_cate_no: 77,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/강동구/47/",
            name: "강동구",
            param: "?cate_no=47",
            cate_no: 47,
            parent_cate_no: 77,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/강북구/48/",
            name: "강북구",
            param: "?cate_no=48",
            cate_no: 48,
            parent_cate_no: 77,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/강서구/49/",
            name: "강서구",
            param: "?cate_no=49",
            cate_no: 49,
            parent_cate_no: 77,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/관악구/50/",
            name: "관악구",
            param: "?cate_no=50",
            cate_no: 50,
            parent_cate_no: 77,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/광진구/51/",
            name: "광진구",
            param: "?cate_no=51",
            cate_no: 51,
            parent_cate_no: 77,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/구로구/52/",
            name: "구로구",
            param: "?cate_no=52",
            cate_no: 52,
            parent_cate_no: 77,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/금천구/53/",
            name: "금천구",
            param: "?cate_no=53",
            cate_no: 53,
            parent_cate_no: 77,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/노원구/54/",
            name: "노원구",
            param: "?cate_no=54",
            cate_no: 54,
            parent_cate_no: 77,
            design_page_url: "product/list.html",
            like_count: 0,
        },
        {
            link_product_list: "/category/도봉구/55/",
            name: "도봉구",
            param: "?cate_no=55",
            cate_no: 55,
            parent_cate_no: 77,
            design_page_url: "product/list.html",
            like_count: 0,
        },
    ],
};
